# Generated by Django 3.2.8 on 2021-10-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tocht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=64, unique=True)),
                ('datum', models.DateField()),
                ('pub_datum', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wandelaar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('pub_datum', models.DateTimeField(auto_now=True)),
                ('tocht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wcc_app.tocht')),
            ],
        ),
    ]
